# Generated by Django 5.1.5 on 2025-02-14 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='welcome_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
