# Generated by Django 5.1.5 on 2025-01-16 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_interest_profile_address_profile_app_updates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_status',
            field=models.CharField(choices=[('IA', 'Inactive'), ('PA', 'Pending Approval'), ('A', 'Active'), ('S', 'Suspended'), ('B', 'Banned'), ('D', 'Deactivated')], default='IA', max_length=2),
        ),
    ]
