# Generated by Django 5.1.5 on 2025-02-20 21:52

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=django.contrib.postgres.indexes.GistIndex(fields=['location'], name='users_profi_locatio_9328c5_gist'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['gender', 'relationship_goal'], name='users_profi_gender_7260a3_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['last_seen'], name='users_profi_last_se_f356e3_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['created_at'], name='users_profi_created_f60c54_idx'),
        ),
    ]
