# Generated by Django 5.1.5 on 2025-01-19 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_old_id_alter_user_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='current_address',
            new_name='selected_address',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='current_country',
            new_name='selected_country',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='current_state',
            new_name='selected_lga',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='lga',
            new_name='selected_state',
        ),
    ]
