# Generated by Django 5.1.5 on 2025-01-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_current_address_profile_selected_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='device_token',
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_verified',
            field=models.CharField(choices=[('UNVERIFIED', 'Not Verified'), ('PENDING', 'Verification Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Verification Rejected')], default='PENDING', max_length=50),
        ),
    ]
