# Generated by Django 5.1.5 on 2025-02-20 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='allow_vip_direct_messages',
            field=models.BooleanField(default=True, help_text='Allow VIP users to message directly'),
        ),
        migrations.AddField(
            model_name='profile',
            name='message_price',
            field=models.PositiveIntegerField(default=0, help_text='Coins required to message this user directly'),
        ),
        migrations.AddField(
            model_name='profile',
            name='require_initial_request',
            field=models.BooleanField(default=True, help_text='Require message requests for first contact'),
        ),
    ]
