# Generated by Django 5.1.5 on 2025-02-21 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_allow_vip_direct_messages_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='allow_vip_direct_messages',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='message_price',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='require_initial_request',
        ),
    ]
