# Generated by Django 5.1.5 on 2025-02-26 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_state_lga'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='state',
            new_name='statee',
        ),
    ]
