# Generated by Django 5.1.5 on 2025-01-28 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_last_active_profile_last_seen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='show_last_active',
            new_name='show_last_seen',
        ),
    ]
