# Generated by Django 5.1.5 on 2025-02-26 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_state_profile_statee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='selected_lga',
            new_name='selected_lgaa',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='selected_state',
            new_name='selected_statee',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='statee',
            new_name='state',
        ),
    ]
