# Generated by Django 5.1.5 on 2025-02-26 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rename_selected_lga_profile_selected_lgaa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='selected_lga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.lga'),
        ),
        migrations.AddField(
            model_name='profile',
            name='selected_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.state'),
        ),
    ]
