# Generated by Django 5.1.5 on 2025-02-28 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_profile_selected_lga_profile_selected_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='selected_lgaa',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='selected_statee',
        ),
        migrations.AlterField(
            model_name='userrating',
            name='rated_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userrating',
            name='rating_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='userrating',
            index=models.Index(fields=['rated_user', 'rating_user'], name='users_userr_rated_u_bdd3ad_idx'),
        ),
        migrations.AddIndex(
            model_name='userrating',
            index=models.Index(fields=['rated_user', 'created_at'], name='users_userr_rated_u_c41268_idx'),
        ),
    ]
