# Generated by Django 5.1.5 on 2025-02-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_profile_profession_alter_profile_selected_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profession',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
