# Generated by Django 5.1.5 on 2025-02-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_profile_profession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='number_of_kids',
        ),
        migrations.AddField(
            model_name='profile',
            name='do_you_have_kids',
            field=models.CharField(choices=[('Y', 'Yes, I have kids'), ('N', 'No, I don’t have kids'), ('D', 'I don’t like kids'), ('A', 'I would like to have kids one day')], default='D'),
        ),
    ]
