# Generated by Django 5.1.5 on 2025-02-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_profile_number_of_kids_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='selected_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='selected_lga',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
