# Generated by Django 5.1.5 on 2025-02-15 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='virtualgift',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='virtualgift',
            name='coins_value',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.CreateModel(
            name='GiftType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=50, unique=True)),
                ('coin_price', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='gifts/images/')),
                ('animation', models.FileField(blank=True, null=True, upload_to='gifts/animations/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['coin_price'],
                'indexes': [models.Index(fields=['key', 'is_active'], name='gift_giftty_key_220a4d_idx')],
            },
        ),
        migrations.AlterField(
            model_name='virtualgift',
            name='gift_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gifts', to='gift.gifttype'),
        ),
        migrations.AddIndex(
            model_name='virtualgift',
            index=models.Index(fields=['sender', 'receiver'], name='gift_virtua_sender__445611_idx'),
        ),
        migrations.AddIndex(
            model_name='virtualgift',
            index=models.Index(fields=['timestamp'], name='gift_virtua_timesta_66a7a0_idx'),
        ),
    ]
