# Generated by Django 5.1.5 on 2025-02-16 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_subscriptionplan_usersubscription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='features',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
