# Generated by Django 5.1.5 on 2025-02-16 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_remove_subscriptionplan_features_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(choices=[('WEEKLY', 'Weekly'), ('MONTH', 'Monthly'), ('THREEMONTH', '3 Month')], max_length=20, unique=True),
        ),
    ]
