# Generated by Django 5.1.5 on 2025-02-24 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_alter_subscriptionplan_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='iap_apple_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='iap_google_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='purchase_method',
            field=models.CharField(choices=[('COINS', 'Coins'), ('PLAY_STORE', 'Play Store'), ('APP_STORE', 'App Store')], default='COINS', max_length=20),
        ),
    ]
