# Generated by Django 5.1.5 on 2025-02-24 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_subscriptionplan_iap_apple_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='title',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
