# Generated by Django 5.1.5 on 2025-02-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[('LIKE', 'Like'), ('SUPER_LIKE', 'Super Like'), ('MATCH', 'Match'), ('MESSAGE', 'Message'), ('VISIT', 'Profile Visit')], max_length=20),
        ),
    ]
