# Generated by Django 5.1.5 on 2025-02-03 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_is_pinned_message_reactions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinnedmessage',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinned_messages', to='chat.message'),
        ),
    ]
