# Generated by Django 5.1.5 on 2025-02-20 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_pinnedmessage_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagerequest',
            name='coins_paid',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='messagerequest',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='messagerequest',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
