# Generated by Django 5.1.5 on 2025-02-21 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_messagerequest_coins_paid_messagerequest_is_paid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagerequest',
            name='coins_paid',
        ),
        migrations.RemoveField(
            model_name='messagerequest',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='messagerequest',
            name='payment_reference',
        ),
    ]
