# Generated by Django 5.1.5 on 2025-03-01 07:21

import django_jsonform.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('all', 'All'), ('android', 'Android'), ('ios', 'iOS')], max_length=10)),
                ('message', models.TextField(default='Our app is currently undergoing maintenance to bring you an even better experience. We apologize for any inconvenience this may cause. Please check back later, and thank you for your patience!')),
                ('is_active', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AppConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_type', models.CharField(choices=[('ad_config', 'Ad Configuration'), ('app_versions', 'App Versions'), ('feature_flags', 'Feature Flags'), ('security', 'Security Keys'), ('app_settings', 'App Settings'), ('third_party', 'Third Party Services'), ('other', 'Not Assign Yet')], default='other', max_length=20)),
                ('platform', models.CharField(choices=[('all', 'All'), ('android', 'Android'), ('ios', 'iOS')], default='all', max_length=10)),
                ('data', django_jsonform.models.fields.JSONField(blank=True)),
                ('version', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('is_secret', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-version'],
                'unique_together': {('config_type', 'platform')},
            },
        ),
    ]
