# Generated by Django 5.1.5 on 2025-02-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('all', 'All'), ('android', 'Android'), ('ios', 'iOS')], max_length=10)),
                ('message', models.TextField()),
                ('is_active', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='appconfiguration',
            old_name='value',
            new_name='data',
        ),
        migrations.AlterUniqueTogether(
            name='appconfiguration',
            unique_together={('config_type', 'platform')},
        ),
        migrations.AddField(
            model_name='appconfiguration',
            name='config_type',
            field=models.CharField(choices=[('ad_config', 'Ad Configuration'), ('app_versions', 'App Versions'), ('feature_flags', 'Feature Flags'), ('security', 'Security Keys'), ('app_settings', 'App Settings'), ('third_party', 'Third Party Services'), ('other', 'Not Assign Yet')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='appconfiguration',
            name='is_secret',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appconfiguration',
            name='platform',
            field=models.CharField(choices=[('all', 'All'), ('android', 'Android'), ('ios', 'iOS')], default='all', max_length=10),
        ),
        migrations.RemoveField(
            model_name='appconfiguration',
            name='key',
        ),
    ]
