# Generated by Django 5.1.5 on 2025-03-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appmaintenance',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
