# Generated by Django 5.1.5 on 2025-02-24 20:47

import django_jsonform.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_alter_appconfiguration_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appconfiguration',
            name='data',
            field=django_jsonform.models.fields.JSONField(blank=True),
        ),
    ]
