# Generated by Django 5.1.5 on 2025-02-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveIntegerField(help_text='Coins per 1 Naira')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
            },
        ),
        migrations.RenameField(
            model_name='paymenttransaction',
            old_name='amount',
            new_name='naira_amount',
        ),
        migrations.RenameField(
            model_name='withdrawalrequest',
            old_name='amount',
            new_name='coins_amount',
        ),
        migrations.RenameField(
            model_name='withdrawalrequest',
            old_name='fee',
            new_name='exchange_rate',
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='exchange_rate',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='fee_percentage',
            field=models.PositiveIntegerField(default=5, help_text='Percentage fee for withdrawal'),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='naira_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
