# Generated by Django 5.1.5 on 2025-02-14 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_coinrate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinrate',
            name='rate',
            field=models.DecimalField(decimal_places=2, help_text='Coins per 1 Naira', max_digits=2),
        ),
    ]
