# Generated by Django 5.1.5 on 2025-03-04 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='swipelimit',
            name='ad_boost_remaining',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
