# Generated by Django 5.1.5 on 2025-01-28 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('liker', 'liked', 'is_active')},
        ),
        migrations.AddIndex(
            model_name='dislike',
            index=models.Index(fields=['disliker', 'disliked'], name='match_disli_dislike_783e05_idx'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['liker', 'liked', 'is_active'], name='match_like_liker_i_416d54_idx'),
        ),
        migrations.AddField(
            model_name='visit',
            name='visited',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visited_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visit',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='visit',
            unique_together={('visitor', 'visited')},
        ),
    ]
