# Generated by Django 5.1.5 on 2025-03-06 09:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_swipelimit_ad_boost_remaining'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('liker', 'liked')},
        ),
    ]
