# Generated by Django 5.1.5 on 2025-02-21 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0003_match_is_premium_match_premium_features_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='premium_features',
        ),
    ]
